# -*- coding: utf-8 -*-

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingWindow(object):
    def setupUi(self, SettingWindow):
        SettingWindow.setObjectName("SettingWindow")
        SettingWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SettingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Terminalcombobox = QtWidgets.QComboBox(self.tab)
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.setObjectName("Terminalcombobox")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Terminalcombobox.sizePolicy().hasHeightForWidth())
        self.Terminalcombobox.setSizePolicy(sizePolicy)
        self.Terminalcombobox.setMinimumSize(QtCore.QSize(0, 35))
        self.verticalLayout_2.addWidget(self.Terminalcombobox)
        self.verticalSpacer = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(self.verticalSpacer)
        self.applybutton = QtWidgets.QPushButton(self.tab)
        self.applybutton.setObjectName("applybutton")
        sizePolicy1 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.applybutton.sizePolicy().hasHeightForWidth())
        self.applybutton.setSizePolicy(sizePolicy1)
        self.applybutton.setMinimumSize(QtCore.QSize(0, 35))
        self.verticalLayout_2.addWidget(self.applybutton)
        self.tabWidget.addTab(self.tab, "")

        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.verticalLayout_4.addWidget(self.label)
        self.cpp_combobox = QtWidgets.QComboBox(self.tab_3)
        self.cpp_combobox.addItem("")
        self.cpp_combobox.addItem("")
        self.cpp_combobox.setObjectName("cpp_combobox")
        self.verticalLayout_4.addWidget(self.cpp_combobox)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.label_2.setFont(font)
        self.verticalLayout_4.addWidget(self.label_2)
        self.c_combobox = QtWidgets.QComboBox(self.tab_3)
        self.c_combobox.addItem("")
        self.c_combobox.addItem("")
        self.c_combobox.setObjectName("c_combobox")
        self.verticalLayout_4.addWidget(self.c_combobox)
        self.verticalSpacer_3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(self.verticalSpacer_3)
        self.applycompilebutton = QtWidgets.QPushButton(self.tab_3)
        self.applycompilebutton.setObjectName("applycompilebutton")
        self.verticalLayout_4.addWidget(self.applycompilebutton)
        self.tabWidget.addTab(self.tab_3, "")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Decompiler_comboBox = QtWidgets.QComboBox(self.tab_2)
        self.Decompiler_comboBox.addItem("")
        self.Decompiler_comboBox.addItem("")
        self.Decompiler_comboBox.setObjectName("Decompiler_comboBox")
        self.verticalLayout_3.addWidget(self.Decompiler_comboBox)
        self.verticalSpacer_2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(self.verticalSpacer_2)
        self.Applydcompiler = QtWidgets.QPushButton(self.tab_2)
        self.Applydcompiler.setObjectName("Applydcompiler")
        self.verticalLayout_3.addWidget(self.Applydcompiler)
        self.tabWidget.addTab(self.tab_2, "")

        self.verticalLayout.addWidget(self.tabWidget)
        SettingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingWindow)

    def retranslateUi(self, SettingWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingWindow.setWindowTitle(_translate("SettingWindow", "Runix-settings"))
        self.Terminalcombobox.setItemText(0, _translate("SettingWindow", "Auto"))
        self.Terminalcombobox.setItemText(1, _translate("SettingWindow", "Kitty"))
        self.Terminalcombobox.setItemText(2, _translate("SettingWindow", "Konsole"))
        self.Terminalcombobox.setItemText(3, _translate("SettingWindow", "Alacritty"))
        self.Terminalcombobox.setItemText(4, _translate("SettingWindow", "Gnome-terminal"))
        self.Terminalcombobox.setItemText(5, _translate("SettingWindow", "Gnome-console"))
        self.Terminalcombobox.setItemText(6, _translate("SettingWindow", "Xfce-Terminal"))
        self.applybutton.setText(_translate("SettingWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingWindow", "Default terminal"))
        self.label.setText(_translate("SettingWindow", "C++ Compiler"))
        self.cpp_combobox.setItemText(0, _translate("SettingWindow", "G++"))
        self.cpp_combobox.setItemText(1, _translate("SettingWindow", "Clang++"))
        self.label_2.setText(_translate("SettingWindow", "C Compiler"))
        self.c_combobox.setItemText(0, _translate("SettingWindow", "Gcc"))
        self.c_combobox.setItemText(1, _translate("SettingWindow", "Clang"))
        self.applycompilebutton.setText(_translate("SettingWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SettingWindow", "Default compiler"))
        self.Decompiler_comboBox.setItemText(0, _translate("SettingWindow", "Objdump"))
        self.Decompiler_comboBox.setItemText(1, _translate("SettingWindow", "Retdec"))
        self.Applydcompiler.setText(_translate("SettingWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SettingWindow", "Default decompiler"))
