# -*- coding: utf-8 -*-

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingWindow(object):
    def setupUi(self, SettingWindow):
        SettingWindow.setObjectName("SettingWindow")
        SettingWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SettingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Terminalcombobox = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Terminalcombobox.sizePolicy().hasHeightForWidth())
        self.Terminalcombobox.setSizePolicy(sizePolicy)
        self.Terminalcombobox.setMinimumSize(QtCore.QSize(0, 35))
        self.Terminalcombobox.setObjectName("Terminalcombobox")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.Terminalcombobox.addItem("")
        self.verticalLayout_2.addWidget(self.Terminalcombobox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.applybutton = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applybutton.sizePolicy().hasHeightForWidth())
        self.applybutton.setSizePolicy(sizePolicy)
        self.applybutton.setMinimumSize(QtCore.QSize(0, 35))
        self.applybutton.setObjectName("applybutton")
        self.verticalLayout_2.addWidget(self.applybutton)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        SettingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingWindow)

    def retranslateUi(self, SettingWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingWindow.setWindowTitle(_translate("SettingWindow", "Runix-settings"))
        self.Terminalcombobox.setItemText(0, _translate("SettingWindow", "Auto"))
        self.Terminalcombobox.setItemText(1, _translate("SettingWindow", "Kitty"))
        self.Terminalcombobox.setItemText(2, _translate("SettingWindow", "Konsole"))
        self.Terminalcombobox.setItemText(3, _translate("SettingWindow", "Alacritty"))
        self.Terminalcombobox.setItemText(4, _translate("SettingWindow", "Gnome-terminal"))
        self.Terminalcombobox.setItemText(5, _translate("SettingWindow", "Gnome-console"))
        self.Terminalcombobox.setItemText(6, _translate("SettingWindow", "Xfce-Terminal"))
        self.applybutton.setText(_translate("SettingWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingWindow", "Default terminal"))
